import type { ComponentMeta } from "./types.ts";

/**
 * Human-authored metadata for every component. Prop tables are extracted
 * automatically from TypeScript (see scripts/extract-api.ts); this file holds
 * the guidance that types cannot express: when, why, accessibility, keyboard.
 */
export const components: ComponentMeta[] = [
  // ───────────────────────── Foundations ─────────────────────────
  {
    name: "box",
    title: "Box",
    category: "foundations",
    description:
      "The lowest-level layout primitive: a div (or any element via `as`) with `asChild` support.",
    when: "Use when you need a semantic wrapper element with styling and no layout opinion.",
    avoid: "Prefer Stack, Grid or Container when you are arranging children.",
    a11y: [
      "Choose the semantic element with `as` (section, nav, article) instead of adding roles.",
    ],
  },
  {
    name: "stack",
    title: "Stack",
    category: "foundations",
    primary: "Stack",
    description:
      "Flex layout with token-based, responsive gap and direction. Also exports HStack, VStack, Flex and Spacer.",
    when: "Use for one-dimensional layouts: form fields, button rows, card content.",
    avoid: "Use Grid for two-dimensional layouts.",
    a11y: [
      "Visual order equals DOM order; avoid `row-reverse` when it would contradict reading order.",
    ],
    responsive:
      '`gap` and `direction` accept responsive objects (`{ base: "column", md: "row" }`) compiled to CSS variables — no client JS.',
  },
  {
    name: "grid",
    title: "Grid",
    category: "foundations",
    description: "CSS grid with responsive columns, gaps and auto-fill by minimum child width.",
    when: "Use for card grids, dashboards and galleries.",
    a11y: ["Grid only affects layout; keep a meaningful source order for screen readers."],
    responsive:
      '`columns={{ base: 1, md: 2, lg: 3 }}` or `minChildWidth="16rem"` for intrinsic responsiveness.',
  },
  {
    name: "container",
    title: "Container",
    category: "foundations",
    description: "Centers content with a consistent max width and responsive gutters.",
    when: "Use once per page section to align content to the layout grid.",
    a11y: ['Use `as="main"` or `as="section"` to create landmarks where appropriate.'],
    responsive: "Gutters grow from 16px (mobile) to 32px (desktop); sizes sm → prose → full.",
  },
  {
    name: "separator",
    title: "Separator",
    category: "foundations",
    description: "Horizontal or vertical divider, optionally with a centered label.",
    when: "Use to separate groups of content or menu sections.",
    a11y: [
      'Decorative by default (`role="none"`). Set `decorative={false}` when the separation is meaningful.',
    ],
  },
  {
    name: "aspect-ratio",
    title: "AspectRatio",
    category: "foundations",
    description: "Reserves space for media at a fixed ratio to prevent layout shift.",
    when: "Use around images, videos, maps and embeds whose size is known in advance.",
    a11y: ["Purely presentational; the media inside needs its own alt text or title."],
  },
  {
    name: "scroll-area",
    title: "ScrollArea",
    category: "foundations",
    description: "Cross-browser styled scroll container that keeps native scrolling behavior.",
    when: "Use for constrained regions such as sidebars, menus and chat logs.",
    avoid: "Avoid nested scroll regions in the main page flow.",
    a11y: [
      "Pass `aria-label` to make the viewport a focusable, named region so keyboard users can scroll it.",
    ],
  },
  {
    name: "resizable",
    title: "Resizable",
    category: "foundations",
    primary: "ResizablePanelGroup",
    description: "Split views with draggable, keyboard-accessible handles.",
    when: "Use for editors, master–detail views and IDE-like layouts on larger screens.",
    avoid: "On mobile, stack panels instead of offering resize handles.",
    a11y: [
      'Handles are `role="separator"` with `aria-valuenow`, focusable and operable by keyboard (dragging is never required).',
    ],
    keyboard: [
      ["← / →", "Resize horizontal panels (mirrored in RTL)"],
      ["↑ / ↓", "Resize vertical panels"],
      ["Home / End", "Minimize / maximize the leading panel"],
    ],
  },
  // ───────────────────────── Typography ─────────────────────────
  {
    name: "typography",
    title: "Typography",
    category: "typography",
    primary: "Text",
    description: "Text, Heading, Label, Caption, Code, Kbd, Link, Blockquote and Prose.",
    when: "Use for all text so sizes, colors and rhythm stay consistent with tokens.",
    a11y: [
      "Heading separates semantic `level` from visual `size` — keep a sequential outline (h1 → h2 → h3).",
      "External links announce that they open in a new tab.",
      "Body text defaults to 16px on mobile with 1.5+ line height.",
    ],
  },
  // ───────────────────────── Buttons ─────────────────────────
  {
    name: "button",
    title: "Button",
    category: "buttons",
    description:
      "Primary action element with variants, sizes, icons and loading state. Also IconButton and ButtonGroup.",
    when: "Use for actions (submit, open, save). Keep one `default` (primary) button per view.",
    avoid: "Use Link (or `asChild` with an anchor) for navigation.",
    a11y: [
      'Renders a native `<button type="button">`; `loading` sets `aria-busy` and disables the button.',
      "IconButton requires `aria-label` and expands its hit area to 44px on touch devices.",
      "Focus ring uses the `ring` token and is always visible for keyboard users.",
    ],
    keyboard: [["Enter / Space", "Activate"]],
    related: ["toggle"],
  },
  {
    name: "toggle",
    title: "Toggle",
    category: "buttons",
    description: "Two-state button (`aria-pressed`) and ToggleGroup with roving focus.",
    when: "Use for formatting toolbars, view switches (list/grid) and filters that apply immediately.",
    avoid: "Use Switch for settings and Checkbox inside forms.",
    a11y: [
      "Toggle exposes `aria-pressed`; ToggleGroup is a single tab stop with arrow-key navigation.",
    ],
    keyboard: [
      ["Enter / Space", "Toggle"],
      ["← / →", "Move between items in a group"],
    ],
  },
  // ───────────────────────── Forms ─────────────────────────
  {
    name: "form",
    title: "Form",
    category: "forms",
    description:
      "Accessible form with zero-config constraint validation, validate-on-blur, async submit and an error summary.",
    when: "Use for every data-entry form. Works standalone or with external errors (server, React Hook Form).",
    a11y: [
      "Validates on submit and re-validates on blur — never on every keystroke.",
      "After a failed submit, focus moves to FormErrorSummary (linking to each invalid field) or the first invalid field.",
      "Inline errors stay next to their fields and are referenced via `aria-describedby`.",
    ],
    related: ["field"],
  },
  {
    name: "field",
    title: "Field",
    category: "forms",
    description:
      "Connects label, control, helper text and error: ids, aria-describedby, aria-invalid, required and disabled.",
    when: "Wrap every form control in a Field so labelling and errors are always correct.",
    a11y: [
      "Labels are always visible — placeholders are not labels.",
      "Required fields show an indicator and set `required` on the control.",
    ],
    related: ["form", "input"],
  },
  {
    name: "input",
    title: "Input",
    category: "forms",
    description: "Single-line text input with sizes, filled variant and invalid state.",
    when: "Use for short free-text values. Set a semantic `type` and `autoComplete`.",
    a11y: [
      "Uses 16px text on mobile to avoid iOS zoom.",
      "Invalid styling is driven by `aria-invalid` so visuals match semantics.",
    ],
  },
  {
    name: "textarea",
    title: "Textarea",
    category: "forms",
    description: "Multi-line input with optional auto-resize and live character count.",
    when: "Use for messages, descriptions and reviews.",
    a11y: ["The character count is announced politely via `aria-live`."],
  },
  {
    name: "number-input",
    title: "NumberInput",
    category: "forms",
    description: "Locale-aware numeric input with steppers, clamping and keyboard support.",
    when: "Use for quantities, guests, prices and other bounded numbers.",
    avoid: "Use Slider for approximate values and Input for identifiers such as phone numbers.",
    a11y: [
      'Exposes `role="spinbutton"` with `aria-valuenow/min/max/text`; parses localized input ("1 234,5", Arabic digits).',
    ],
    keyboard: [
      ["↑ / ↓", "Increment / decrement"],
      ["PageUp / PageDown", "Step ×10"],
      ["Home / End", "Min / max"],
    ],
  },
  {
    name: "password-input",
    title: "PasswordInput",
    category: "forms",
    description: "Password field with an accessible show/hide toggle.",
    when: "Use for sign-in and account creation.",
    a11y: [
      "Never blocks paste or password managers (WCAG 2.2 accessible authentication).",
      "The toggle announces its state with `aria-pressed`.",
    ],
  },
  {
    name: "search-input",
    title: "SearchInput",
    category: "forms",
    description:
      "Search field with icon, clear button, loading state and optional global shortcut.",
    when: "Use for search boxes in headers, tables and directories.",
    a11y: [
      'Wrapped in `role="search"`; Escape clears; the shortcut hint is hidden from screen readers.',
    ],
    keyboard: [
      ["Enter", "Submit search"],
      ["Escape", "Clear"],
      ["Shortcut (e.g. ⌘K)", "Focus the field"],
    ],
  },
  {
    name: "input-group",
    title: "InputGroup",
    category: "forms",
    description: "Wraps an input with leading/trailing addons (icons, units, buttons).",
    when: "Use for currency prefixes, unit suffixes and inline actions.",
    a11y: ["Addons are visual; include units in the label or description for screen readers."],
  },
  {
    name: "checkbox",
    title: "Checkbox",
    category: "forms",
    description: "Binary or indeterminate choice, plus CheckboxGroup for multiple values.",
    when: "Use for independent options and consent inside forms.",
    avoid: "Use Switch for settings that apply immediately.",
    a11y: [
      "Supports `indeterminate` (announced as mixed).",
      "CheckboxGroup renders a fieldset with legend.",
    ],
    keyboard: [["Space", "Toggle"]],
  },
  {
    name: "radio-group",
    title: "RadioGroup",
    category: "forms",
    description: "Single choice from a small set; includes Radio and card-style RadioCard.",
    when: "Use for 2–6 mutually exclusive options that should all be visible.",
    avoid: "Use Select or Combobox for longer lists.",
    a11y: ["The group is a single tab stop; arrows move and select."],
    keyboard: [["↑ ↓ ← →", "Move and select"]],
  },
  {
    name: "switch",
    title: "Switch",
    category: "forms",
    description: "On/off control that takes effect immediately.",
    when: "Use for settings and preferences.",
    avoid: "Use Checkbox when the change only applies on submit.",
    a11y: ['Exposes `role="switch"` with `aria-checked`.'],
    keyboard: [["Space / Enter", "Toggle"]],
  },
  {
    name: "select",
    title: "Select",
    category: "forms",
    primary: "SelectTrigger",
    description:
      "Custom single-select listbox with groups, typeahead and collision-aware positioning.",
    when: "Use for choosing one option from 5–15 options.",
    avoid:
      "Use RadioGroup for fewer options, Combobox for long/searchable lists, NativeSelect on mobile-heavy forms.",
    a11y: ["Implements the ARIA listbox pattern with typeahead."],
    keyboard: [
      ["Enter / Space / ↓", "Open"],
      ["↑ / ↓", "Move"],
      ["Type", "Jump to option"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "native-select",
    title: "NativeSelect",
    category: "forms",
    description: "Styled native <select>: zero JS, OS pickers on mobile.",
    when: "Use in server-rendered forms and mobile-first flows.",
    a11y: ["Native semantics and platform accessibility for free."],
  },
  {
    name: "combobox",
    title: "Combobox",
    category: "forms",
    description:
      "Searchable single-select with groups, descriptions, async results and form submission.",
    when: "Use for long lists: countries, categories, users, cities.",
    a11y: [
      'Trigger exposes `role="combobox"`; results use `aria-activedescendant` so focus stays in the search field.',
    ],
    keyboard: [
      ["↑ / ↓", "Move through results"],
      ["Enter", "Select"],
      ["Escape", "Close"],
    ],
    related: ["command", "multi-select", "autocomplete"],
  },
  {
    name: "multi-select",
    title: "MultiSelect",
    category: "forms",
    description: "Searchable multiple selection with removable chips and a max limit.",
    when: "Use for tags, amenities, categories and assignees.",
    a11y: ["Each chip has a labelled remove button; the listbox is `aria-multiselectable`."],
  },
  {
    name: "autocomplete",
    title: "Autocomplete",
    category: "forms",
    description: "Free-text input with fuzzy suggestions (the value need not be a suggestion).",
    when: "Use for search boxes with suggestions, addresses and tags.",
    avoid: "Use Combobox when the value must be one of the options.",
    a11y: ['ARIA combobox with `aria-autocomplete="list"` and `aria-activedescendant`.'],
    keyboard: [
      ["↓", "Open / next suggestion"],
      ["Enter", "Accept suggestion"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "slider",
    title: "Slider",
    category: "forms",
    description: "Single value or range selection along a track (RangeSlider).",
    when: "Use for approximate values: price ranges, distance, volume.",
    a11y: [
      "Each thumb has an accessible name (`thumbLabels`) and `aria-valuetext` from `formatValue`.",
    ],
    keyboard: [
      ["← → ↑ ↓", "Step (mirrored in RTL)"],
      ["PageUp / PageDown", "Large step"],
      ["Home / End", "Min / max"],
    ],
  },
  {
    name: "otp-input",
    title: "OTPInput",
    category: "forms",
    description: "One-time code entry with paste, SMS autofill and grouping.",
    when: "Use for verification codes and PINs.",
    a11y: [
      'Group is labelled; each box announces its position; `autocomplete="one-time-code"` enables autofill.',
    ],
    keyboard: [
      ["← / →", "Move between digits"],
      ["Backspace", "Delete and move back"],
    ],
  },
  {
    name: "file-upload",
    title: "FileUpload",
    category: "forms",
    primary: "Dropzone",
    description: "Dropzone and managed file list with validation, progress and removal.",
    when: "Use for documents, photos and attachments.",
    a11y: [
      "Drag-and-drop is optional: a real button opens the file picker.",
      "Rejected files are reported via `onFilesRejected` with a reason.",
    ],
  },
  // ───────────────────────── Date & time ─────────────────────────
  {
    name: "calendar",
    title: "Calendar",
    category: "date-time",
    description:
      "Accessible month grid for single dates and ranges; also MonthPicker and YearPicker.",
    when: "Use inline for availability views or inside date pickers.",
    a11y: [
      'ARIA grid pattern with localized day names, first day of week and `aria-current="date"` for today.',
    ],
    keyboard: [
      ["← → ↑ ↓", "Move by day/week (mirrored in RTL)"],
      ["Home / End", "Start / end of week"],
      ["PageUp / PageDown", "Previous / next month (+Shift: year)"],
      ["Enter / Space", "Select"],
    ],
  },
  {
    name: "date-picker",
    title: "DatePicker",
    category: "date-time",
    description: "Date, date range and date-time pickers in a popover calendar.",
    when: "Use for bookings, filters and scheduling.",
    avoid:
      "For birth dates, three native inputs (day/month/year) are often faster than a calendar.",
    a11y: [
      "The trigger is a button announcing the selected date; values submit as ISO strings via `name`.",
    ],
    responsive: "DateRangePicker shows two months on wide screens and one on phones.",
  },
  {
    name: "time-picker",
    title: "TimePicker",
    category: "date-time",
    description: "Searchable time selector with locale-formatted options and min/max/step.",
    when: "Use for appointment times and opening hours.",
    a11y: ["Values are `HH:mm`; display follows the locale's 12/24h convention."],
  },
  // ───────────────────────── Navigation ─────────────────────────
  {
    name: "navbar",
    title: "Navbar",
    category: "navigation",
    description: "Site/app header with brand, links, actions and a mobile menu sheet.",
    when: "Use as the primary top navigation on every page, in the same place.",
    a11y: [
      'Current page uses `aria-current="page"`; the mobile menu is a labelled dialog that closes on navigation.',
    ],
    responsive: "Links collapse into NavbarMobileMenu below `md`.",
  },
  {
    name: "sidebar",
    title: "Sidebar",
    category: "navigation",
    primary: "SidebarProvider",
    description:
      "Collapsible app sidebar (icon rail on desktop, sheet on mobile) with groups, items, badges and shortcut.",
    when: "Use for dashboards and apps with many sections.",
    a11y: [
      "Collapsed items keep their names for screen readers and show tooltips.",
      "SidebarTrigger exposes `aria-expanded`.",
    ],
    keyboard: [["⌘B / Ctrl+B", "Toggle the sidebar"]],
    responsive: "Below `md` the sidebar becomes a slide-in sheet.",
  },
  {
    name: "navigation-menu",
    title: "NavigationMenu",
    category: "navigation",
    description: "Website navigation with dropdown panels (mega menus).",
    when: "Use for marketing sites with grouped destinations.",
    a11y: ["Panels open on hover and on Enter/Space; links remain reachable in order."],
    keyboard: [
      ["Tab", "Move between top-level items"],
      ["Enter / Space / ↓", "Open panel"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    category: "navigation",
    description: "Hierarchy trail with separators (flipped in RTL) and ellipsis.",
    when: "Use on pages 3+ levels deep.",
    a11y: ['Landmark `nav` with a label; the current page uses `aria-current="page"`.'],
  },
  {
    name: "pagination",
    title: "Pagination",
    category: "navigation",
    description:
      "Page navigation with crawlable links or buttons, ellipses and a compact mobile mode.",
    when: "Use for search results and listings; link mode for SEO.",
    avoid: "Consider infinite loading only when position does not matter.",
    a11y: ['Current page `aria-current="page"`; each link is labelled ("Go to page 4").'],
    responsive: 'Shows "Page x of y" with prev/next on small screens.',
  },
  {
    name: "stepper",
    title: "Stepper",
    category: "navigation",
    description:
      "Progress through a multi-step flow with completed, current, upcoming and error states.",
    when: "Use for checkout, onboarding and multi-step forms.",
    a11y: [
      'Current step has `aria-current="step"`; completed steps are announced and can be revisited.',
    ],
  },
  {
    name: "menubar",
    title: "Menubar",
    category: "navigation",
    description: "Desktop-application style menu bar.",
    when: "Use in editors and complex tools on desktop.",
    a11y: ["Implements the ARIA menubar pattern."],
    keyboard: [
      ["← / →", "Move between menus"],
      ["↓ / Enter", "Open menu"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "navigation-rail",
    title: "NavigationRail",
    category: "navigation",
    description: "Compact vertical navigation (icon + label) for tablets.",
    when: "Use between phone bottom navigation and desktop sidebars.",
    a11y: ["Items always show text labels; current item uses `aria-current`."],
  },
  {
    name: "mobile-navigation",
    title: "MobileNavigation",
    category: "navigation",
    description: "Bottom tab bar for top-level destinations on phones.",
    when: "Use for 3–5 top-level destinations in mobile-first apps.",
    a11y: ["Respects safe areas; warns in development when more than five items are used."],
    responsive: "Hidden from `md` up (set `showOnDesktop` to keep it).",
  },
  {
    name: "skip-link",
    title: "SkipLink",
    category: "navigation",
    description: "Visually hidden link that appears on focus to skip to main content.",
    when: "Render as the first element of every page layout.",
    a11y: ['Targets `#main`; SidebarInset renders `<main id="main" tabindex="-1">`.'],
  },
  // ───────────────────────── Overlays ─────────────────────────
  {
    name: "dialog",
    title: "Dialog",
    category: "overlays",
    description: "Modal window for focused tasks (also exported as Modal).",
    when: "Use Dialog for focused actions that need full attention: edit, create, confirm details.",
    avoid:
      "Use Sheet for contextual side panels, Drawer on mobile, AlertDialog for destructive confirmations, and never for primary navigation.",
    a11y: [
      "Traps focus, restores it to the trigger, closes on Escape and locks page scroll.",
      "Always has a visible close button and a title (DialogTitle).",
      "Nested dialogs stack correctly.",
    ],
    keyboard: [
      ["Escape", "Close"],
      ["Tab / Shift+Tab", "Cycle focus inside"],
    ],
  },
  {
    name: "alert-dialog",
    title: "AlertDialog",
    category: "overlays",
    description: "Interrupting confirmation for consequential or destructive actions.",
    when: "Use before deleting, discarding changes or irreversible actions.",
    a11y: ['`role="alertdialog"`; focus starts on Cancel; clicking outside does not dismiss.'],
    keyboard: [["Escape", "Cancel"]],
  },
  {
    name: "sheet",
    title: "Sheet",
    category: "overlays",
    description: "Edge-anchored panel (start, end, top, bottom) with logical sides for RTL.",
    when: "Use Sheet for mobile-oriented contextual panels: filters, navigation, details.",
    a11y: ["Same focus management as Dialog."],
    responsive: "Widths clamp to the viewport; bottom sheets respect safe areas.",
  },
  {
    name: "drawer",
    title: "Drawer",
    category: "overlays",
    description: "Bottom drawer with drag-to-dismiss handle for mobile-first flows.",
    when: "Use Drawer when content should remain spatially connected to the current page on phones.",
    a11y: ["Dragging is optional: Escape, the overlay and close buttons also dismiss it."],
  },
  {
    name: "popover",
    title: "Popover",
    category: "overlays",
    description: "Non-modal floating panel anchored to a trigger.",
    when: "Use for pickers, quick settings and small forms.",
    a11y: ["Focus moves into the popover and returns to the trigger on close."],
    keyboard: [["Escape", "Close"]],
  },
  {
    name: "tooltip",
    title: "Tooltip",
    category: "overlays",
    description: "Short supplementary label on hover and keyboard focus.",
    when: "Use to name icon buttons or show shortcuts.",
    avoid: "Never put essential or interactive content in tooltips — they do not exist on touch.",
    a11y: ["Appears on focus as well as hover; linked with `aria-describedby`."],
  },
  {
    name: "hover-card",
    title: "HoverCard",
    category: "overlays",
    description: "Rich preview for sighted pointer users (profile previews).",
    when: "Use as an enhancement for links that already work on their own.",
    a11y: ["Not announced to screen readers; content must be available elsewhere."],
  },
  {
    name: "dropdown-menu",
    title: "DropdownMenu",
    category: "overlays",
    description:
      "Menu of actions with items, checkboxes, radios, shortcuts and submenus (also exported as Dropdown).",
    when: 'Use for overflow actions and "more" menus.',
    a11y: [
      "ARIA menu pattern with typeahead; destructive items are styled and labelled, not only colored.",
    ],
    keyboard: [
      ["Enter / Space / ↓", "Open and focus first item"],
      ["↑ / ↓", "Move"],
      ["→ / ←", "Open / close submenu (mirrored in RTL)"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "context-menu",
    title: "ContextMenu",
    category: "overlays",
    description: "Right-click / long-press menu.",
    when: "Use as a shortcut to actions that are also available elsewhere.",
    a11y: ["Opens with Shift+F10 / the context-menu key."],
  },
  // ───────────────────────── Feedback ─────────────────────────
  {
    name: "alert",
    title: "Alert",
    category: "feedback",
    description:
      "Inline contextual message (info, success, warning, destructive) and page-level Banner.",
    when: "Use for messages tied to a section or the whole page.",
    a11y: ["Icons pair color with shape.", "`live` makes new alerts announce (role alert/status)."],
  },
  {
    name: "toast",
    title: "Toast",
    category: "feedback",
    primary: "Toaster",
    description:
      "Sonner-style notifications: `toast.success()`, promise toasts, actions (Undo), queueing.",
    when: "Use for brief confirmations and background results.",
    avoid: "Do not use toasts for errors that need action — show them inline.",
    a11y: [
      "Polite live region; errors are assertive. Toasts never steal focus.",
      "Pause on hover/focus; default duration 5s; reachable via Alt+T.",
    ],
    keyboard: [["Alt+T", "Focus notifications"]],
  },
  {
    name: "progress",
    title: "Progress",
    category: "feedback",
    description: "Linear and circular progress, determinate or indeterminate.",
    when: "Use for uploads and multi-step processes with known progress.",
    a11y: ['`role="progressbar"` with value text; label via `label` or `aria-label`.'],
  },
  {
    name: "spinner",
    title: "Spinner",
    category: "feedback",
    description: "Indeterminate activity indicator.",
    when: "Use for short waits inside buttons or small areas.",
    avoid: "Use Skeleton for content-shaped loading longer than ~1s.",
    a11y: [
      '`role="status"` with a label; pass `label={null}` when a parent already announces loading.',
    ],
  },
  {
    name: "skeleton",
    title: "Skeleton",
    category: "feedback",
    description: "Placeholder shapes that reserve layout while content loads.",
    when: "Use for lists, cards and tables while data loads.",
    a11y: [
      "Hidden from assistive tech; set `aria-busy` on the container. Shimmer stops with reduced motion.",
    ],
  },
  {
    name: "state",
    title: "EmptyState",
    category: "feedback",
    primary: "EmptyState",
    description: "EmptyState, ErrorState, SuccessState and LoadingState templates.",
    when: "Use whenever a view has no data, failed, or finished — always offer a next step.",
    a11y: ['ErrorState uses `role="alert"`; success/loading use `role="status"`.'],
  },
  // ───────────────────────── Data display ─────────────────────────
  {
    name: "card",
    title: "Card",
    category: "data-display",
    description:
      "Composable content container: header, title, description, action, media, content, footer and stretched link.",
    when: "Use to group related content and for listing items.",
    a11y: [
      "For clickable cards use one CardLink (stretched) so the card has a single, named link.",
    ],
  },
  {
    name: "badge",
    title: "Badge",
    category: "data-display",
    description: "Short status or metadata label; CountBadge for numeric counts.",
    when: "Use for statuses (Paid, Open), categories and counts.",
    a11y: ["Status is conveyed by text, not only color; CountBadge accepts a descriptive label."],
  },
  {
    name: "tag",
    title: "Tag",
    category: "data-display",
    description: "Categorization label (optionally removable) and selectable Chip.",
    when: "Use Tag for applied filters/keywords and Chip for quick filter toggles.",
    a11y: ['Remove buttons are labelled ("Remove Vegan"); Chip uses `aria-pressed`.'],
  },
  {
    name: "avatar",
    title: "Avatar",
    category: "data-display",
    description: "Image with initials fallback, presence status and AvatarGroup overflow.",
    when: "Use for people, businesses and brands.",
    a11y: ['Named via `name`; the `+n` overflow is announced ("3 more").'],
  },
  {
    name: "table",
    title: "Table",
    category: "data-display",
    description:
      "Semantic table primitives with sortable headers, density-aware cells and stacked mobile layout.",
    when: "Use for static or server-rendered tabular data.",
    a11y: ["Sortable headers expose `aria-sort`; scrollable tables are focusable, named regions."],
    responsive: '`responsive="stack"` turns rows into labelled cards below `md`.',
  },
  {
    name: "data-table",
    title: "DataTable",
    category: "data-display",
    description:
      "Sorting, search, filtering, pagination, row selection, bulk actions, column visibility, loading and empty states. DataGrid adds cell navigation.",
    when: "Use for admin lists and dashboards; `manual` mode for server-side data.",
    avoid: "For very large datasets (10k+ rows) add virtualization or server paging.",
    a11y: [
      "Selection checkboxes are labelled; bulk-action bar is a status region; DataGrid supports arrow-key cell navigation.",
    ],
    keyboard: [["← → ↑ ↓ (DataGrid)", "Move between cells"]],
  },
  {
    name: "list",
    title: "List",
    category: "data-display",
    description: "Semantic list with rich rows (start, title, description, end).",
    when: "Use for settings rows, contacts and simple feeds.",
    a11y: ["Renders `ul`/`ol` so item counts are announced."],
  },
  {
    name: "stat",
    title: "Stat",
    category: "data-display",
    description: "Key figures with trend (Stat, StatCard, StatGroup, Metric).",
    when: "Use for dashboard KPIs.",
    a11y: [
      "Rendered as description lists; trends use icon + text, not color alone; tabular figures.",
    ],
  },
  {
    name: "timeline",
    title: "Timeline",
    category: "data-display",
    description: "Chronological events with icons and times.",
    when: "Use for activity logs, order tracking and history.",
    a11y: ["Ordered list with `<time dateTime>`."],
  },
  {
    name: "tree",
    title: "Tree",
    category: "data-display",
    description: "Hierarchical list with expand/collapse, selection and typeahead.",
    when: "Use for file browsers and nested categories.",
    a11y: ["ARIA tree pattern with levels, set size and position."],
    keyboard: [
      ["↑ / ↓", "Move"],
      ["→ / ←", "Expand / collapse (mirrored in RTL)"],
      ["Home / End", "First / last"],
      ["Enter / Space", "Select"],
      ["*", "Expand siblings"],
    ],
  },
  {
    name: "accordion",
    title: "Accordion",
    category: "data-display",
    description: "Stacked disclosures (single or multiple), default/separated/bordered.",
    when: "Use for FAQs and secondary details.",
    a11y: ["Triggers are buttons inside headings with `aria-expanded`."],
    keyboard: [
      ["Enter / Space", "Toggle"],
      ["↑ / ↓", "Move between headers"],
    ],
  },
  {
    name: "collapsible",
    title: "Collapsible",
    category: "data-display",
    description: "A single show/hide region.",
    when: 'Use for "show more" sections and advanced options.',
    a11y: ["Trigger exposes `aria-expanded` and `aria-controls`."],
  },
  {
    name: "tabs",
    title: "Tabs",
    category: "navigation",
    description: "Switch between related views (line, pills, enclosed; horizontal or vertical).",
    when: "Use for peer views of the same object.",
    avoid: "Do not use tabs for sequential steps (use Stepper).",
    a11y: [
      "ARIA tabs with automatic or manual activation.",
      "Tab `value`s are used to build element ids — use slugs without spaces.",
    ],
    keyboard: [
      ["← / →", "Previous / next tab (mirrored in RTL)"],
      ["Home / End", "First / last tab"],
    ],
    responsive: "Tab lists scroll horizontally on narrow screens.",
  },
  {
    name: "carousel",
    title: "Carousel",
    category: "media",
    description: "Scroll-snap carousel with controls, dots and pausable autoplay.",
    when: "Use for galleries and featured content on small screens.",
    avoid: "Avoid hiding important content in auto-rotating carousels.",
    a11y: [
      "Swipe is optional (prev/next buttons); autoplay pauses on hover, focus and reduced motion and has a pause button.",
    ],
    keyboard: [["← / →", "Previous / next slide"]],
  },
  // ───────────────────────── Media ─────────────────────────
  {
    name: "media",
    title: "Image",
    category: "media",
    primary: "Image",
    description:
      "Image (reserved ratio, lazy, fallback), ImageGallery, Lightbox, Video (captions) and Audio (transcript).",
    when: "Use for all content media.",
    a11y: [
      "`alt` is required (empty for decorative).",
      "Video accepts caption tracks; Audio can link a transcript; Lightbox supports arrow keys.",
    ],
  },
  // ───────────────────────── Command ─────────────────────────
  {
    name: "command",
    title: "Command",
    category: "command",
    description:
      "Keyboard-first command palette with fuzzy search, groups, shortcuts, async loading and CommandDialog (⌘K).",
    when: "Use for global search, quick actions and power-user navigation.",
    a11y: [
      "Input is a combobox with `aria-activedescendant`; groups are labelled; empty/loading states are announced.",
    ],
    keyboard: [
      ["⌘K / Ctrl+K", "Open CommandDialog"],
      ["↑ / ↓", "Move"],
      ["Enter", "Run"],
      ["Escape", "Close"],
    ],
  },
  {
    name: "highlight",
    title: "Highlight",
    category: "command",
    description: "Highlights matched terms (accent-insensitive) with <mark>.",
    when: "Use in search results and suggestions.",
    a11y: ["Uses `<mark>`; do not rely on highlight color to convey meaning."],
  },
  // ───────────────────────── Patterns ─────────────────────────
  {
    name: "business-card",
    title: "BusinessCard",
    category: "patterns",
    description:
      "Generic listing card for businesses and places, with PlaceCard, RestaurantCard, HotelCard and ServiceCard presets.",
    when: "Use in directories, local discovery and search results.",
    a11y: ["One stretched link per card; rating, price level and status are announced as text."],
  },
  {
    name: "product-card",
    title: "ProductCard",
    category: "patterns",
    description: "Marketplace product tile with price, rating, badges and actions.",
    when: "Use in product grids and recommendations.",
    a11y: ["Actions stay independently focusable above the stretched link."],
  },
  {
    name: "article-card",
    title: "ArticleCard",
    category: "patterns",
    description:
      "Editorial card with image, category, author, date and reading time (vertical, horizontal, featured).",
    when: "Use for blogs, news and guides.",
    a11y: ["Rendered as `<article>` with `<time dateTime>`."],
  },
  {
    name: "event-card",
    title: "EventCard",
    category: "patterns",
    description: "Event listing with localized date block, time range and venue.",
    when: "Use for events, classes and bookings.",
    a11y: ["Dates are machine-readable (`<time>`)."],
  },
  {
    name: "profile-card",
    title: "ProfileCard",
    category: "patterns",
    description: "Person or organization summary with stats and actions.",
    when: "Use for team pages, hosts, sellers and authors.",
    a11y: ["Stats render as a description list."],
  },
  {
    name: "review-card",
    title: "ReviewCard",
    category: "patterns",
    description: "Customer review with rating, expandable text and footer (owner reply).",
    when: "Use on business, product and service pages.",
    a11y: ['"Read more" is a button with `aria-expanded`.'],
  },
  {
    name: "category-card",
    title: "CategoryCard",
    category: "patterns",
    description: "Category tile (icon + name + count) and CityCard (image with scrim).",
    when: "Use for browse-by-category and destination grids.",
    a11y: ["Text over images uses a gradient scrim to keep contrast."],
  },
  {
    name: "rating",
    title: "Rating",
    category: "patterns",
    description: "Interactive Rating (radio group) and read-only ReviewStars with fractional fill.",
    when: "Use for reviews and feedback.",
    a11y: ['Rating is a native radio group; ReviewStars is announced as "4.5 out of 5 stars".'],
    keyboard: [["← / →", "Change rating"]],
  },
  {
    name: "price",
    title: "Price",
    category: "patterns",
    description:
      "Locale-aware Price (discounts, periods), PriceRange, PriceLevel ($$) and Currency.",
    when: "Use anywhere money is shown.",
    a11y: [
      "Previous prices have hidden labels; PriceLevel has a text alternative; tabular figures.",
    ],
  },
  {
    name: "location",
    title: "Location",
    category: "patterns",
    description: "Address line with distance and LocationCard with directions.",
    when: "Use on listing cards and business pages.",
    a11y: ["Rendered as `<address>`; directions link opens a maps app."],
  },
  {
    name: "opening-hours",
    title: "OpeningHours",
    category: "patterns",
    description: 'Weekly hours table and live OpenStatus ("Open · closes 6 PM"), overnight-aware.',
    when: "Use on business pages and cards.",
    a11y: ['Status uses a dot plus text; today is marked with `aria-current="date"`.'],
  },
  {
    name: "filter-panel",
    title: "FilterPanel",
    category: "patterns",
    description:
      "Sidebar filters on desktop and a sheet on mobile from the same children; FilterSection and FilterChips.",
    when: "Use for search and listing pages.",
    a11y: ["Applied filters are removable tags in a labelled group."],
    responsive: "Below `lg` filters open in a bottom sheet with an active-count badge.",
  },
  {
    name: "search-result",
    title: "SearchResult",
    category: "patterns",
    description:
      "Search hit with highlighted terms and SearchResults container with announced summary.",
    when: "Use for site search and directory results.",
    a11y: ["The results summary is a status region so counts are announced."],
  },
  {
    name: "map-placeholder",
    title: "MapPlaceholder",
    category: "patterns",
    description:
      "Dependency-free map stand-in with accessible pins, plus MapPanel list/map layout.",
    when: "Use before integrating a map provider, or as a lightweight static map.",
    a11y: [
      "Pins are labelled buttons; the region has a descriptive label. Always offer a list alternative.",
    ],
    responsive: "MapPanel stacks the map above the list on mobile.",
  },
  {
    name: "lead-form",
    title: "LeadForm",
    category: "patterns",
    description:
      "Contact/quote form with validation and success state, plus ClaimBusiness call-to-action.",
    when: "Use for lead generation and business claiming flows.",
    a11y: ["Visible labels, autocomplete hints, error summary and consent checkbox."],
  },
  {
    name: "premium-badge",
    title: "PremiumBadge",
    category: "patterns",
    description: "PremiumBadge, VerifiedBadge and FeaturedBadge.",
    when: "Use to mark paid, verified or featured listings.",
    a11y: ["Always include text, not only an icon or color."],
  },
  // ───────────────────────── Theming ─────────────────────────
  {
    name: "color-mode-toggle",
    title: "ColorModeToggle",
    category: "theming",
    description: "Button switching between light and dark mode via UIProvider.",
    when: "Use in headers and settings.",
    a11y: ['Label describes the action ("Switch to dark mode").'],
  },
  {
    name: "icon",
    title: "Icon",
    category: "theming",
    description: 'Dynamic `<Icon name="search" />` and `createIcon` for custom glyphs.',
    when: "Use for data-driven icons; import icons directly for smallest bundles.",
    a11y: ["Decorative by default; pass `title` or `aria-label` for meaningful icons."],
  },
  {
    name: "visually-hidden",
    title: "VisuallyHidden",
    category: "theming",
    description: "Hides content visually while keeping it available to screen readers.",
    when: "Use to add context to icon-only or visual-only UI.",
    a11y: ["Prefer visible text whenever possible."],
  },
];
