/**
 * Indexes demos/*.tsx: builds a lazy loader map (demos/index.ts) and the
 * source code of every example (demos/sources.json) for "Show code".
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = join(dirname(fileURLToPath(import.meta.url)), "../demos");
const files = readdirSync(dir).filter((f) => f.endsWith(".tsx") && !f.startsWith("_"));

const sources: Record<string, Record<string, string>> = {};
const order: Record<string, string[]> = {};
for (const file of files) {
  const name = file.replace(/\.tsx$/, "");
  const text = readFileSync(join(dir, file), "utf8");
  const imports = text
    .split("\n")
    .filter((l) => l.startsWith("import "))
    .filter((l) => !l.includes('from "./_'))
    .join("\n");
  const parts = text.split(/\n(?=export function )/);
  sources[name] = {};
  order[name] = [];
  for (const part of parts.slice(1)) {
    const match = /^export function (\w+)/.exec(part);
    if (!match) continue;
    const body = part.trim();
    sources[name][match[1]!] = `${imports}\n\n${body}\n`;
    order[name].push(match[1]!);
  }
}

writeFileSync(join(dir, "sources.json"), JSON.stringify(sources));
writeFileSync(
  join(dir, "index.ts"),
  "// Generated by scripts/collect-demos.ts. Do not edit.\nimport type { ComponentType } from \"react\";\n\n" +
    "export type DemoModule = Record<string, ComponentType>;\n\n" +
    `export const demoOrder: Record<string, string[]> = ${JSON.stringify(order, null, 2)};\n\n` +
    "export const demoLoaders: Record<string, () => Promise<DemoModule>> = {\n" +
    files.map((f) => `  ${JSON.stringify(f.replace(/\.tsx$/, ""))}: () => import(${JSON.stringify(`./${f.replace(/\.tsx$/, "")}`)}) as Promise<DemoModule>,`).join("\n") +
    "\n};\n",
);
console.log(`Collected ${Object.values(order).flat().length} examples from ${files.length} demo modules.`);
