/**
 * Photos from Wikimedia Commons, used under their free licenses.
 * Generated from the Commons API; each entry keeps its author and license so
 * the /credits page can attribute them. Do not remove credits when reusing.
 */
export interface Photo {
  src: string;
  alt: string;
  title: string;
  page: string;
  author: string;
  license: string;
  licenseUrl: string;
}

export const photos = {
  hero: {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Navagio%2C_Zante_01.jpg/1280px-Navagio%2C_Zante_01.jpg",
    alt: "Navagio shipwreck beach framed by white cliffs on Zakynthos, Greece",
    title: "Navagio, Zante 01.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Navagio,_Zante_01.jpg",
    author: "Wilnel José Verdú Guerrero",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "santorini-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Oia_sunset_-_panoramio_%282%29.jpg/1280px-Oia_sunset_-_panoramio_%282%29.jpg",
    alt: "Sunset over the whitewashed houses of Oia, Santorini",
    title: "Oia sunset - panoramio (2).jpg",
    page: "https://commons.wikimedia.org/wiki/File:Oia_sunset_-_panoramio_(2).jpg",
    author: "TomasEE",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
  },
  "santorini-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Santorini_Fira3_tango7174.jpg/1280px-Santorini_Fira3_tango7174.jpg",
    alt: "Fira's clifftop town above the Santorini caldera",
    title: "Santorini Fira3 tango7174.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Santorini_Fira3_tango7174.jpg",
    author: "Tango7174",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "santorini-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Ancient_Akrotiri.jpeg/1280px-Ancient_Akrotiri.jpeg",
    alt: "Excavated Bronze Age streets at Akrotiri, Santorini",
    title: "Ancient Akrotiri.jpeg",
    page: "https://commons.wikimedia.org/wiki/File:Ancient_Akrotiri.jpeg",
    author: "Rt44",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "kyoto-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/1280px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg",
    alt: "Tunnel of vermilion torii gates at Fushimi Inari Taisha, Kyoto",
    title: "Torii path with lantern at Fushimi Inari Taisha Shrine, Kyoto, Japan.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg",
    author: "Basile Morin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "kyoto-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg/1280px-Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg",
    alt: "The Golden Pavilion of Kinkaku-ji reflected in its pond",
    title: "Golden Pavilion Kinkaku-ji water mirror 2024.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg",
    author: "Nacaru",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "kyoto-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Arashiyama%2C_Part_II_-_Arashiyama7534.jpg/1280px-Arashiyama%2C_Part_II_-_Arashiyama7534.jpg",
    alt: "Forested hills and river at Arashiyama, Kyoto",
    title: "Arashiyama, Part II - Arashiyama7534.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Arashiyama,_Part_II_-_Arashiyama7534.jpg",
    author: "lumoplank",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
  },
  "kyoto-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Kiyomizu.jpg/1280px-Kiyomizu.jpg",
    alt: "Kiyomizu-dera temple's wooden stage among trees",
    title: "Kiyomizu.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Kiyomizu.jpg",
    author: "Jordy Meow",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "kyoto-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/150124_Gion_Kyoto_Japan01s3.jpg/1280px-150124_Gion_Kyoto_Japan01s3.jpg",
    alt: "Traditional wooden machiya houses along a street in Gion",
    title: "150124 Gion Kyoto Japan01s3.jpg",
    page: "https://commons.wikimedia.org/wiki/File:150124_Gion_Kyoto_Japan01s3.jpg",
    author: "663highland",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
  },
  "marrakech-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Djemaa_el_Fna.jpg/1280px-Djemaa_el_Fna.jpg",
    alt: "Crowds and food stalls in Jemaa el-Fnaa square, Marrakech",
    title: "Djemaa el Fna.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Djemaa_el_Fna.jpg",
    author: "Boris Macek",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "marrakech-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Le_jardin_des_majorelle_40.JPG/1280px-Le_jardin_des_majorelle_40.JPG",
    alt: "Cobalt-blue villa and cacti in the Majorelle Garden",
    title: "Le jardin des majorelle 40.JPG",
    page: "https://commons.wikimedia.org/wiki/File:Le_jardin_des_majorelle_40.JPG",
    author: "Viault",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "marrakech-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Marokko0112_%28retouched%29.jpg/1280px-Marokko0112_%28retouched%29.jpg",
    alt: "Minaret of the Koutoubia Mosque against a blue sky",
    title: "Marokko0112 (retouched).jpg",
    page: "https://commons.wikimedia.org/wiki/File:Marokko0112_(retouched).jpg",
    author: "Rol1000",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "marrakech-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Bahia_Palace_large_court.jpg/1280px-Bahia_Palace_large_court.jpg",
    alt: "Tiled courtyard of the Bahia Palace, Marrakech",
    title: "Bahia Palace large court.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Bahia_Palace_large_court.jpg",
    author: "Val Traveler",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "bali-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Ubud_%2849818456887%29.jpg/1280px-Ubud_%2849818456887%29.jpg",
    alt: "Green rice fields and palms near Ubud, Bali",
    title: "Ubud (49818456887).jpg",
    page: "https://commons.wikimedia.org/wiki/File:Ubud_(49818456887).jpg",
    author: "Jorge Franganillo",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
  },
  "bali-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Pura_Ulun_Danu_Bratan%2C_2022.jpg/1280px-Pura_Ulun_Danu_Bratan%2C_2022.jpg",
    alt: "Pura Ulun Danu Bratan temple on the shore of Lake Bratan",
    title: "Pura Ulun Danu Bratan, 2022.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Pura_Ulun_Danu_Bratan,_2022.jpg",
    author: "LukeTriton",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "bali-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Pura_Luhur_Uluwatu_2017-08-17_%2834%29.jpg/1280px-Pura_Luhur_Uluwatu_2017-08-17_%2834%29.jpg",
    alt: "Uluwatu temple on a clifftop above the Indian Ocean",
    title: "Pura Luhur Uluwatu 2017-08-17 (34).jpg",
    page: "https://commons.wikimedia.org/wiki/File:Pura_Luhur_Uluwatu_2017-08-17_(34).jpg",
    author: "Paskuu",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "bali-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/View_Of_Mt.Batur_on_April_8th_2026.jpg/1280px-View_Of_Mt.Batur_on_April_8th_2026.jpg",
    alt: "Mount Batur volcano rising above the caldera",
    title: "View Of Mt.Batur on April 8th 2026.jpg",
    page: "https://commons.wikimedia.org/wiki/File:View_Of_Mt.Batur_on_April_8th_2026.jpg",
    author: "WikiSantaClaus",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
  },
  "bali-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Broken_Bay%2C_Nusa_Penida.jpg/1280px-Broken_Bay%2C_Nusa_Penida.jpg",
    alt: "Broken Bay's natural rock arch on Nusa Penida",
    title: "Broken Bay, Nusa Penida.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Broken_Bay,_Nusa_Penida.jpg",
    author: "Georgi Kovachev",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "swiss-alps-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Matterhorn_from_Domh%C3%BCtte_-_2.jpg/1280px-Matterhorn_from_Domh%C3%BCtte_-_2.jpg",
    alt: "The Matterhorn's pyramid peak above a glacier",
    title: "Matterhorn from Domhütte - 2.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Matterhorn_from_Domh%C3%BCtte_-_2.jpg",
    author: "Photo: chil, on Camptocamp.org\nDerivative work:Zacharie Grossen",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "swiss-alps-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Sphinx_et_Jungfrau_-_img_06980.jpg/1280px-Sphinx_et_Jungfrau_-_img_06980.jpg",
    alt: "Sphinx observatory at Jungfraujoch with the Jungfrau behind",
    title: "Sphinx et Jungfrau - img 06980.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Sphinx_et_Jungfrau_-_img_06980.jpg",
    author: "Pmau",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "swiss-alps-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/20190725_Oeschinensee-Panorama%2C_Kandersteg_%2806540-42_stitch%29.jpg/1280px-20190725_Oeschinensee-Panorama%2C_Kandersteg_%2806540-42_stitch%29.jpg",
    alt: "Turquoise Oeschinen Lake surrounded by Alpine cliffs",
    title: "20190725 Oeschinensee-Panorama, Kandersteg (06540-42 stitch).jpg",
    page: "https://commons.wikimedia.org/wiki/File:20190725_Oeschinensee-Panorama,_Kandersteg_(06540-42_stitch).jpg",
    author: "Günter Seggebäing, Coesfeld",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "swiss-alps-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/CH_Landwasser_2.jpg/1280px-CH_Landwasser_2.jpg",
    alt: "Train crossing the Landwasser Viaduct in the Swiss Alps",
    title: "CH Landwasser 2.jpg",
    page: "https://commons.wikimedia.org/wiki/File:CH_Landwasser_2.jpg",
    author: "Daniel Schwen",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
  },
  "swiss-alps-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/1_lauterbrunnen_valley_wengen_2022.jpg/1280px-1_lauterbrunnen_valley_wengen_2022.jpg",
    alt: "Lauterbrunnen valley with waterfalls and meadows",
    title: "1 lauterbrunnen valley wengen 2022.jpg",
    page: "https://commons.wikimedia.org/wiki/File:1_lauterbrunnen_valley_wengen_2022.jpg",
    author: "Chensiyuan",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "lisbon-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Torre_Bel%C3%A9m_April_2009-4a.jpg/1280px-Torre_Bel%C3%A9m_April_2009-4a.jpg",
    alt: "Belém Tower on the bank of the Tagus river",
    title: "Torre Belém April 2009-4a.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Torre_Bel%C3%A9m_April_2009-4a.jpg",
    author: "Alvesgaspar",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "lisbon-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Lisbon_alfalma.jpg/1280px-Lisbon_alfalma.jpg",
    alt: "Rooftops of the Alfama district, Lisbon",
    title: "Lisbon alfalma.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Lisbon_alfalma.jpg",
    author: "Arne Müseler",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
  },
  "lisbon-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/The_Jer%C3%B3nimos_Monastery_or_Hieronymites_Monastery.png/1280px-The_Jer%C3%B3nimos_Monastery_or_Hieronymites_Monastery.png",
    alt: "Jerónimos Monastery's ornate limestone façade",
    title: "The Jerónimos Monastery or Hieronymites Monastery.png",
    page: "https://commons.wikimedia.org/wiki/File:The_Jer%C3%B3nimos_Monastery_or_Hieronymites_Monastery.png",
    author: "Heartshade",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
  },
  "lisbon-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Sintra_Portugal_Pal%C3%A1cio_da_Pena-01.jpg/1280px-Sintra_Portugal_Pal%C3%A1cio_da_Pena-01.jpg",
    alt: "The colourful Pena Palace above Sintra's forests",
    title: "Sintra Portugal Palácio da Pena-01.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Sintra_Portugal_Pal%C3%A1cio_da_Pena-01.jpg",
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "lisbon-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Lisboa_-_Portugal_%2852597836992%29.jpg/1280px-Lisboa_-_Portugal_%2852597836992%29.jpg",
    alt: "Lisbon's hills and river viewed from above",
    title: "Lisboa - Portugal (52597836992).jpg",
    page: "https://commons.wikimedia.org/wiki/File:Lisboa_-_Portugal_(52597836992).jpg",
    author: "Vitor Oliveira from Torres Vedras, PORTUGAL",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
  },
  "patagonia-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg/1280px-Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg",
    alt: "Granite towers and horns of Torres del Paine",
    title: "Torres del Paine y cuernos del Paine, montaje.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Torres_del_Paine_y_cuernos_del_Paine,_montaje.jpg",
    author:
      "Karen Chan 16 y Miguel.v ( local | logs | global ) (originales), y Jorge Morales Piderit (montaje).",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
  },
  "patagonia-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Perito_Moreno_Glacier_2023.jpg/1280px-Perito_Moreno_Glacier_2023.jpg",
    alt: "The ice front of Perito Moreno Glacier",
    title: "Perito Moreno Glacier 2023.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Perito_Moreno_Glacier_2023.jpg",
    author: "Fernando",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "patagonia-4": {
    src: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Glaciar_Grey%2C_Torres_del_Paine.jpg",
    alt: "Icebergs in front of Grey Glacier, Torres del Paine",
    title: "Glaciar Grey, Torres del Paine.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Glaciar_Grey,_Torres_del_Paine.jpg",
    author: "welsh boy from London, U.K.",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
  },
  "patagonia-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Los_Cuernos_de_Torres_del_Paine.jpg/1280px-Los_Cuernos_de_Torres_del_Paine.jpg",
    alt: "Los Cuernos peaks above a lake in Torres del Paine",
    title: "Los Cuernos de Torres del Paine.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Los_Cuernos_de_Torres_del_Paine.jpg",
    author: "Natalia Reyes Escobar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "norwegian-fjords-1": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Geirangerfjord_.jpg/1280px-Geirangerfjord_.jpg",
    alt: "Geirangerfjord between steep green mountainsides",
    title: "Geirangerfjord .jpg",
    page: "https://commons.wikimedia.org/wiki/File:Geirangerfjord_.jpg",
    author: "Andreas Trepte",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
  },
  "norwegian-fjords-2": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Fl%C3%A5msbana.jpg/1280px-Fl%C3%A5msbana.jpg",
    alt: "The Flåm railway train in a mountain valley",
    title: "Flåmsbana.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Fl%C3%A5msbana.jpg",
    author: "Karen",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
  },
  "norwegian-fjords-3": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Lyse_Fjord_et_Preikestolen.jpg/1280px-Lyse_Fjord_et_Preikestolen.jpg",
    alt: "Preikestolen cliff high above the Lysefjord",
    title: "Lyse Fjord et Preikestolen.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Lyse_Fjord_et_Preikestolen.jpg",
    author: "Clementp.fr",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "norwegian-fjords-4": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Bryggen%2C_Bergen%2C_Noruega%2C_2019-09-08%2C_DD_115-117_PAN.jpg/1280px-Bryggen%2C_Bergen%2C_Noruega%2C_2019-09-08%2C_DD_115-117_PAN.jpg",
    alt: "Colourful wooden warehouses of Bryggen, Bergen",
    title: "Bryggen, Bergen, Noruega, 2019-09-08, DD 115-117 PAN.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Bryggen,_Bergen,_Noruega,_2019-09-08,_DD_115-117_PAN.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "norwegian-fjords-5": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Naer%C3%B8yfjorden.jpg/1280px-Naer%C3%B8yfjorden.jpg",
    alt: "Calm waters of the narrow Nærøyfjord",
    title: "Naerøyfjorden.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Naer%C3%B8yfjorden.jpg",
    author: "Karamell",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "stay-caldera-view-suites": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Imerovigli_01.jpg/1280px-Imerovigli_01.jpg",
    alt: "Cliffside suites of Imerovigli overlooking the caldera",
    title: "Imerovigli 01.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Imerovigli_01.jpg",
    author: "Bernard Gagnon",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "stay-ryokan-hanami": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Tamatsukuri_onsen_yado02s3648.jpg/1280px-Tamatsukuri_onsen_yado02s3648.jpg",
    alt: "Traditional ryokan inn with tatami rooms and a garden",
    title: "Tamatsukuri onsen yado02s3648.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Tamatsukuri_onsen_yado02s3648.jpg",
    author: "663highland",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
  },
  "stay-kyoto-station-hotel": {
    src: "https://upload.wikimedia.org/wikipedia/commons/3/30/Kamogawa_sakura.jpg",
    alt: "Cherry blossoms along the Kamo River, Kyoto",
    title: "Kamogawa sakura.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Kamogawa_sakura.jpg",
    author: "Moja",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
  },
  "stay-uluwatu-surf-house": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Padang_Padang_Beach_Bali.jpg/1280px-Padang_Padang_Beach_Bali.jpg",
    alt: "Padang Padang beach between rocky cliffs, Bali",
    title: "Padang Padang Beach Bali.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Padang_Padang_Beach_Bali.jpg",
    author: "TMFalkner",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "stay-zermatt-chalet": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/1_zermatt_evening_2022.jpg/1280px-1_zermatt_evening_2022.jpg",
    alt: "Zermatt village at dusk below the mountains",
    title: "1 zermatt evening 2022.jpg",
    page: "https://commons.wikimedia.org/wiki/File:1_zermatt_evening_2022.jpg",
    author: "Chensiyuan",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "tour-cyclades-sailing-week": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Naxos_%CE%9D%CE%AC%CE%BE%CE%BF%CF%82_2020-08-20_02_Chora_Grotta_and_Vintzi_beaches.jpg/1280px-Naxos_%CE%9D%CE%AC%CE%BE%CE%BF%CF%82_2020-08-20_02_Chora_Grotta_and_Vintzi_beaches.jpg",
    alt: "Turquoise bays below Naxos town in the Cyclades",
    title: "Naxos Νάξος 2020-08-20 02 Chora Grotta and Vintzi beaches.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Naxos_%CE%9D%CE%AC%CE%BE%CE%BF%CF%82_2020-08-20_02_Chora_Grotta_and_Vintzi_beaches.jpg",
    author: "Manfred Werner (Tsui)",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
  },
  "tour-atlas-and-sahara": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Merzouga_Dunes_2011.jpg/1280px-Merzouga_Dunes_2011.jpg",
    alt: "Golden sand dunes of Erg Chebbi near Merzouga",
    title: "Merzouga Dunes 2011.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Merzouga_Dunes_2011.jpg",
    author: "Bjørn Christian Tørrissen",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
  },
  "tour-kyoto-food-and-temples": {
    src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Nishiki_Ichiba_by_matsuyuki.jpg/1280px-Nishiki_Ichiba_by_matsuyuki.jpg",
    alt: "Covered food stalls of Nishiki Market, Kyoto",
    title: "Nishiki Ichiba by matsuyuki.jpg",
    page: "https://commons.wikimedia.org/wiki/File:Nishiki_Ichiba_by_matsuyuki.jpg",
    author: "matsuyuki",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
  },
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;

/** Photo URL at a standard Wikimedia thumbnail width (use 960 for cards). */
export const sized = (photo: Photo, width: 960 | 1280 = 1280) =>
  width === 1280 ? photo.src : photo.src.replace("/1280px-", "/960px-");
