/**
 * Generates packages/react/src/components/<name>/README.md from the
 * registry metadata and the extracted API (run `pnpm api` first).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { components } from "../registry/components.ts";
import { CATEGORY_LABELS } from "../registry/types.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const api = JSON.parse(readFileSync(join(root, "registry/api.json"), "utf8")) as Record<
  string,
  Record<
    string,
    {
      kind: string;
      description?: string;
      props: Array<{
        name: string;
        type: string;
        required: boolean;
        default?: string;
        description?: string;
      }>;
      inherits?: string;
    }
  >
>;

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

for (const meta of components) {
  const exports = api[meta.name] ?? {};
  const componentExports = Object.entries(exports).filter(([, d]) => d.kind === "component");
  const primary = meta.primary ?? meta.title.replace(/\s/g, "");
  const ordered = componentExports.sort(([a], [b]) => (a === primary ? -1 : b === primary ? 1 : 0));
  const lines: string[] = [
    `# ${meta.title}`,
    "",
    `> ${CATEGORY_LABELS[meta.category]} · \`@ux-sting/react/${meta.name}\``,
    "",
    meta.description,
    "",
    "## When to use",
    "",
    meta.when,
    ...(meta.avoid ? ["", `**Consider alternatives:** ${meta.avoid}`] : []),
    "",
    "## Installation",
    "",
    "Use the package (tree-shakeable per-component entry point):",
    "",
    "```tsx",
    `import { ${
      componentExports
        .slice(0, 3)
        .map(([n]) => n)
        .join(", ") || primary
    } } from "@ux-sting/react/${meta.name}";`,
    "```",
    "",
    "Or copy the source into your project and own it:",
    "",
    "```bash",
    `npx ux-sting add ${meta.name}`,
    "```",
    "",
    "## Accessibility",
    "",
    ...meta.a11y.map((a) => `- ${a}`),
  ];
  if (meta.keyboard?.length) {
    lines.push(
      "",
      "### Keyboard",
      "",
      "| Keys | Action |",
      "| --- | --- |",
      ...meta.keyboard.map(([k, a]) => `| ${esc(k)} | ${esc(a)} |`),
    );
  }
  if (meta.responsive) lines.push("", "## Responsive behavior", "", meta.responsive);
  lines.push("", "## API");
  for (const [name, doc] of ordered) {
    lines.push("", `### ${name}`, "");
    if (doc.description) lines.push(doc.description.split("\n").join(" "), "");
    if (doc.props.length) {
      lines.push("| Prop | Type | Default | Description |", "| --- | --- | --- | --- |");
      for (const p of doc.props) {
        lines.push(
          `| \`${p.name}\`${p.required ? " *" : ""} | \`${esc(p.type)}\` | ${p.default ? `\`${esc(p.default)}\`` : "—"} | ${esc(p.description ?? "")} |`,
        );
      }
    } else {
      lines.push("No additional props.");
    }
    if (doc.inherits) lines.push("", `_Also accepts ${doc.inherits}._`);
  }
  lines.push(
    "",
    "---",
    "",
    `Full documentation with live examples: \`apps/docs\` → \`/components/${meta.name}\`. This file is generated by \`pnpm readmes\`.`,
    "",
  );
  writeFileSync(
    join(root, "packages/react/src/components", meta.name, "README.md"),
    lines.join("\n"),
  );
}
console.log(`Generated ${components.length} component READMEs.`);
